service: shortcut

provider:
    name: aws
    region: eu-west-2
    runtime: provided.al2

plugins:
    - ./vendor/bref/bref

functions:
    eventbridge:
        handler: EventBridgeHandler.php
        description: 'Function to upload a detailed report about team progress to shortcut'
        timeout: 120
        environment:
            API_KEY: ${env:SHORTCUT_API_KEY}
            DEV_EMAILS: ${env:DEV_EMAILS}
            DEV_LABELS: ${env:DEV_LABELS}
        events:
            - eventBridge:
                schedule: cron(30 23 * * ? *) # Scheduled for every day at 23:30
        layers:
            - ${bref:layer.php-81}
    api:
        handler: ApiHandler.php
        description: 'Function to upload a detailed report about team progress to shortcut'
        timeout: 120
        environment:
            API_KEY: ${env:SHORTCUT_API_KEY}
            DEV_EMAILS: ${env:DEV_EMAILS}
            DEV_LABELS: ${env:DEV_LABELS}
        events:
            - httpApi: "GET /shortcut"
        layers:
            - ${bref:layer.php-81}

# Exclude files from deployment
package:
    patterns:
        - '!tests/**'
